### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by laurengarcia** [3box/3box-comments-react#16] opened 2019-10-30 22:39 UTC
Doesn't seem to support Typescript, no `index.d.ts` file present...
Also tried via `npm i @types/3box-comments-react` ... but got 404
Please add this ASAP!
Should be quick :)

**Comment by oed** [comment] 2019-10-31 09:58
There is no typescript support since this is not a typescript project :) 
Feel free to contribute types to http://definitelytyped.org/ !

**Comment by laurengarcia** [comment] 2019-10-31 20:45
I could shim in a solution for myself that fixes my own immediate problem, but it will result in duplicated effort in your ecosystem... on the other hand if i submit the solution to definitelytyped, i'm on the hook to maintain it and if its not my primary project then its going to fall out of date and probably result in alot of unhappy customers on your side.

(...I also have no idea if the other person in your Discord having build trouble with TS was able to resolve it, and if it even had anything to do with Typescript in the first place or some other issue elsewhere in your pipes...)

Most of the dapps in cryptoland use Typescript from what i've seen.
This request will be a frequent and recurring theme :)

**Comment by oznekenzo** [comment] 2019-11-11 19:14
Saw a lot of long winded tutorials on adding ts support, but seems its as simple as just adding the index.d.ts file - hoping this is the case.
This file has been added, would be great for @laurengarcia to test with the `3box-comments-react@0.0.1-beta.15` npm beta release - once that's confirmed to work, will publish and can add support to our other components

**Comment by oznekenzo** [comment] 2019-11-11 21:33
@laurengarcia thanks for the help on this one - closing

**Closed as completed by oznekenzo** 2019-11-11 21:33 UTC
Labels: enhancement

**Comment by laurengarcia** [comment] 2019-11-12 18:15
Hi @oznekenzo I wish I could guarantee for sure that the `index.d.ts` you added worked w/ TS. Simple definitions file like this has worked for me in the past to support TS on smaller packages with very simple interfaces. I tried adding it to my project yesterday but ended up giving up -- my react app was "ejected" from `create-react-app` and has a very complex webpack configuration (ugh), and unfortunately I couldnt figure out how to splice `3box-comments-react` into it. It was difficult to debug because the 3box index.js is a very large file(!) and my code editor could barely even display, let alone ctrl-f or scroll thru to see what might be the issue.

Sorry I couldnt be more help on this front but I'm out of time. 
Might circle back on this later (in a few months).

**Comment by oznekenzo** [comment] 2019-11-12 19:15
We don't have TS support in the main 3box.js package at the moment, so perhaps ejecting your react app required you interface directly with 3box.js instead of though `3box-comments-react` (I don't know whether you are depending on `3box` elsewhere or if its coming in through the comments plugin).  Is it just now a matter of providing the type interface for the `3box` lib?

**Comment by laurengarcia** [comment] 2019-11-12 19:50
My workaround is lazy-loading 3box.js from the 3box CDN and adding it to my react app on the fly in the browser. In other words, I'm side-stepping the "build" step, so i don't have to worry about 3box.js TS at this point, but it would be nice to have. The downside of this approach being that i dont get the nice UI from this pkg, but it works for what i need to do for now.

**Comment by laurengarcia** [comment] 2019-11-13 22:41
Figured it out, just leaving a note for some other poor soul out there who may be using `create-react-app` in "ejected" mode (meaning all webpack and .tsconfig configs are unbundled so they can be customized): 

You may need to set `"allowSyntheticDefaultImports": true,` in your `.tsconfig` file so it can consume and be backward-compatible with ES5 modules (like this one) that use `module.exports` (vs. ES6 import/export syntax).
